#!/bin/env perl

use strict;

my $pc = 0;
my %labels;
my @inst;

while (<>){
    chomp;
    s/[ \t]+/ /g;
    s/^([^;]*);.*$/$1/;
    s/^ (.*)$/$1/;
    s/^(.+) $/$1/;
    if (s/^([a-zA-Z0-9_-]+:)[ ]*(.*)$/$2/){
	$labels{$1} = $pc;
    }
    /^[\w]*$/ and next;
    print "error: pc $pc when inst size ", scalar(@inst), "\n" if $pc != scalar(@inst);
    ++$pc;
    s/\./$pc/g;
    push @inst, $_;
}

for my $pc (0..scalar @inst - 1){
    my $inst = $inst[$pc];
    my @words = split(" ",$inst);

    for (@words){
	my $target = $labels{$_};
	$_ = $target if defined($target);
    }

    print join(" ", @words), "\n";
}
