sorting: sorting.lid driver.dylan sorting-exports.dylan binary-insertion-sort.dylan comb-sort-11.dylan comb-sort-predefined.dylan insertion-sort.dylan merge-sort.dylan weak-heap-sort.dylan
	d2c sorting.lid

clean:
	-rm -f *.o *.s *.a *.c *.mak *~ sorting sorting.exe
	-rm -rf .libs
