Module:    creatures-genes
Synopsis:  Classes for reading Creatures genetic files
Author:    Chris Double
Copyright: (C) 1998, Chris Double.  All rights reserved.
License:   See License.txt

define constant <chemical> = <byte>;

define constant $chemical-descriptions = #(
    "<NONE>",
    "Pain",
    "Need for Pleasure",
    "Hunger",
    "Coldness",
    "Hotness",
    "Tiredness",
    "Sleepiness",
    "Loneliness",
    "Crowded",
    "Fear", // 10
    "Boredom",
    "Anger",
    "Sex Drive",
    "Injury",
    "Suffocation",
    "Thirst",
    "Stress",
    "Pain Increase",
    "Need for Pleasure Increase",
    "Hunger Increase", //20
    "Coldness Increase",
    "Hotness Increase",
    "Tiredness Increase",
    "Sleepiness Increase",
    "Loneliness Increase",
    "Crowded Increase",
    "Fear Increase",
    "Boredom Increase",
    "Anger Increase",
    "Sex Drive Increase", //30
    "Injury Increase",
    "Suffocation Increase",
    "Thirst Increase",
    "Stress Increase",
    "Pain Decrease (Endorphin)",
    "Need for Pleasure Decrease",
    "Hunger Decrease (Saccharin)",
    "Coldness Decrease",
    "Hotness Decrease",
    "Tiredness Decrease", //40
    "Sleepiness Decrease",
    "Loneliness Decrease",
    "Crowded Decrease",
    "Fear Decrease",
    "Boredom Decrease",
    "Anger Decrease",
    "Sex Drive Decrease",
    "Injury Decrease",
    "Suffocation Decrease",
    "Thirst Decrease", //50
    "Stress Decrease",
    "Reward",
    "Punishment",
    "Reinforcement",
    "ConASH",
    "DecASH1",
    "Reward Echo",
    "Punish Echo",
    "DecASH2",
    "60", //60
    "61",
    "62",
    "63",
    "64",
    "65",
    "66",
    "67",
    "Lactate",
    "Pyruvate",
    "Glucose", //70
    "Fatty Acid",
    "Glycogen",
    "Starch",
    "Fat",
    "Adipose Tissue",
    "Life",
    "Muscle Tissue",
    "Triglyceride",
    "Protein",
    "Amino Acid", //80
    "81",
    "82",
    "83",
    "84",
    "85",
    "86",
    "87",
    "88",
    "89",
    "Dissolved Carbon Dioxide", //90
    "91",
    "Urea",
    "Ammonia",
    "94",
    "Oxygen",
    "Air",
    "Water",
    "Energy",
    "ATP",
    "ADP", //100
    "Myoglobin",
    "Oxymyoglobin",
    "103",
    "Bilin",
    "Oestrogen",
    "Testosterone",
    "Gonadotrophin",
    "Progesterone",
    "Inhibin",
    "LH",
    "FSH",
    "Steroidone",
    "Cholesterol",
    "Arousal Potential",
    "Mating Pheromone",
    "Species Pheromone",
    "Parent Pheromone",
    "Child Pheromone",
    "Sibling Pheromone",
    "Opposite Sex Pheromone",
    "Norn Smell",
    "Grendel smell",
    "Ettin smell",
    "124",
    "125",
    "126",
    "127",
    "128",
    "129",
    "130",
    "131",
    "132",
    "133",
    "134",
    "135",
    "136",
    "137",
    "138",
    "139",
    "Heavy Metals",
    "Cyanide",
    "142",
    "Belladonna",
    "Geddonase",
    "Glycotoxin",
    "Fullness",
    "147",
    "148",
    "149",
    "Vitamin E",
    "Vitamin C",
    "Bile Acid",
    "Insulin",
    "Glycogen Synthetase",
    "Dehydrogenase",
    "Prostaglandin",
    "EDTA",
    "Sodium thiosulphite",
    "Arnica",
    "160",
    "161",
    "162",
    "163",
    "164",
    "165",
    "166",
    "167",
    "Tyrosine",
    "Triptophan",
    "Alcohol",
    "Dancing",
    "Adrenaline",
    "Hexokinase",
    "Activase",
    "Turnase",
    "Collapsase",
    "Downatrophin",
    "Upatrophin",
    "Phosphoglycerokinase",
    "Protease",
    "181",
    "182",
    "183",
    "184",
    "185",
    "186",
    "187",
    "188",
    "189",
    "190",
    "191",
    "192",
    "193",
    "194",
    "195",
    "196",
    "197",
    "198",
    "199",
    "200",
    "201",
    "202",
    "203",
    "204",
    "205",
    "206",
    "207",
    "208",
    "209",
    "210",
    "211",
    "212",
    "213",
    "214",
    "215",
    "216",
    "217",
    "218",
    "219",
    "220",
    "221",
    "222",
    "223",
    "224",
    "225",
    "226",
    "227",
    "228",
    "229",
    "230",
    "231",
    "Histamine A",
    "Histamine B",
    "Sleep toxin",
    "Fever toxin",
    "unknown toxin",
    "unknown toxin",
    "unknown toxin",
    "unknown toxin",
    "Antibody 0",
    "Antibody 1",
    "Antibody 2",
    "Antibody 3",
    "Antibody 4",
    "Antibody 5",
    "Antibody 6",
    "Antibody 7",
    "Antigen 0",
    "Antigen 1",
    "Antigen 2",
    "Antigen 3",
    "Antigen 4",
    "Antigen 5",
    "Antigen 6",
    "Antigen 7"
);

define constant $c3-chemical-descriptions = #(
    "<NONE>",
    "Lactate",
    "Pyruvate",
    "Glucose",
    "Glycogen",
    "Starch",
    "Fatty Acid",
    "Cholesterol",
    "Triglyceride",
    "Adipose Tissue",
    "Fat", //10
    "Muscle Tissue",
    "Protein",
    "Amino Acid",
    "14", //"Fullness (CA)",
    "15",
    "16",
    "Downatrophin",
    "Upatrophin",
    "19", //"Turnase (CA)",
    "20", //"Collapsase (CA)", //20
    "21", //"Dancing (CA)",
    "22",
    "23",
    "Dissolved carbon dioxide",
    "Urea",
    "Ammonia",
    "27",
    "28",
    "Air",
    "Oxygen", //30
    "31", //"Myoglobin (CA)",
    "32", //"Oxymyoglobin (CA)",
    "Water",
    "Energy",
    "ATP",
    "ADP",
    "37",
    "38",
    "Arousal Potential",
    "Libido lowerer", //40
    "Opposite Sex Pheromone",
    "42", //"Hormonase (CA)",
    "43", //"Hormonase2 (CA)",
    "44",
    "45",
    "Oestrogen",
    "47", //"Parturase (CA)",
    "Progesterone",
    "49", //"LH (CA)",
    "50", //"NCG (CA)", //50
    "51",
    "52",
    "Testosterone",
    "Inhibin",
    "55",
    "56",
    "57", //"Species Pheramone (CA)",
    "58", //"Parent Pheramone (CA)",
    "59", //"Child Pheramone (CA)",
    "60", //"Sibling Pheramone (CA)", //60
    "61", //"Norn smell (CA)",
    "62", //"Grendel smell (CA)",
    "63", //"Ettin smell (CA)",
    "64",
    "65",
    "Heavy Metals",
    "Cyanide",
    "Belladonna",
    "Geddonase",
    "Glycotoxin", //70
    "Sleep toxin",
    "Fever toxin",
    "Histamine A",
    "Histamine B",
    "Alcohol",
    "76", //"Tyrosine (CA)",
    "77", //"Triptophan (CA)",
    "78", //"ATP Decoupler (CA)",
    "Carbon Monoxide", //" Myoglobin toxin",
    "Fear toxin", //80
    "Muscle toxin",
    "Antigen 0",
    "Antigen 1",
    "Antigen 2",
    "Antigen 3",
    "Antigen 4",
    "Antigen 5",
    "Antigen 6",
    "Antigen 7",
    "90", //90
    "91",
    "Medicine one",
    "Anti-oxidant", //"Medicine two",
    "Prostaglandin",
    "EDTA",
    "Sodium thiosulphite",
    "Arnica",
    "Vitamin E",
    "Vitmain C",
    "Antihistamine", //"100", //100
    "101",
    "Antibody 0",
    "Antibody 1",
    "Antibody 2",
    "Antibody 3",
    "Antibody 4",
    "Antibody 5",
    "Antibody 6",
    "Antibody 7",
    "110", //110
    "111",
    "Anabolic steriod",
    "Pistle",
    "Insulin",
    "Glucolase",
    "Dehydrogenase",
    "Adrenalin",
    "Grendel nitrate", //"Steroidone",
    "Ettin nitrate", //"Glycogen synthetase",
    "120", //"Bilin", // 120
    "121", //"Protease",
    "122", //"Hexokinase",
    "123", //"Bile acid",
    "Activase",
    "Life",
    "126", //"CAdv Exercise meter",
    "Injury",
    "Stress",
    "Sleepase",
    "130", //130
    "Pain backup",
    "Hunger for protein backup",
    "Hunger for carb backup",
    "Hunger for fat backup",
    "Coldness backup",
    "Hotness backup",
    "Tiredness backup",
    "Sleepiness backup",
    "Loneliness backup",
    "Crowded backup", //140
    "Fear backup",
    "Boredom backup",
    "Anger backup",
    "Sex drive backup",
    "Comfort backup", //"Obedience backup",
    "146",
    "147",
    "Pain",
    "Hunger for protein",
    "Hunger for carbohydrate", //150
    "Hunger for fat",
    "Coldness", 
    "Hotness",
    "Tiredness",
    "Sleepiness",
    "Loneliness",
    "Crowded",
    "Fear",
    "Boredom",
    "Anger", //160
    "Sex drive",
    "Comfort",
    "163",
    "164",
    "CA smell 0 (sound)",
    "CA smell 1 (light)",
    "CA smell 2 (heat)",
    "CA smell 3 (water)",
    "CA smell 4 (nutrient)",
    "CA smell 5 (water)", //170
    "CA smell 6 (protein)",
    "CA smell 7 (carbohydrate)",
    "CA smell 8 (fat)",
    "CA smell 9 (flowers)",
    "CA smell 10 (machinery)",
    "CA smell 11 (?)",
    "CA smell 12 (Norn)",
    "CA smell 13 (Grendel)",
    "CA smell 14 (Ettin)",
    "CA smell 15 (Norn home)", //180
    "CA smell 16 (Grendel home)",
    "CA smell 17 (Ettin home)",
    "CA smell 18 (?)",
    "CA smell 19 (?)",
    "185",
    "186",
    "Stress (H4C)",
    "Stress (H4P)",
    "Stress (H4F)", 
    "Stress (Anger)", //190
    "Stress (Fear)",
    "Stress (Pain)",
    "Stress (Sleep)",
    "Stress (Tired)",
    "Stress (Crowded)",
    "196",
    "197",
    "Brain chemical 1", //"Disappointment",
    "Up",
    "Down", //200
    "Exit",
    "Enter",
    "Wait",
    "Reward", //"Brain chemical 7",
    "Punishment", //"Brain chemical 8",
    "Brain chemical 9",
    "Brain chemical 10",
    "Brain chemical 11", //"Reward",
    "Brain chemical 12", //"Punishment",
    "Brain chemical 13", //210
    "Brain chemical 14",
    "Pre-REM sleep", //"Brain chemical 15",
    "REM sleep", //"LongTerm Weight Relax",
    "214",
    "215",
    "216",
    "217",
    "218",
    "219",
    "220",
    "221",
    "222",
    "223",
    "224",
    "225",
    "226",
    "227",
    "228",
    "229",
    "230",
    "231",
    "232",
    "233",
    "234",
    "235",
    "236",
    "237",
    "238",
    "239",
    "240",
    "241",
    "242",
    "243",
    "244",
    "245",
    "246",
    "247",
    "248",
    "249",
    "250",
    "251",
    "252",
    "253",
    "254",
    "255"
);

define generic convert-to-chemical-description( version, type :: <chemical> ) => (result :: <string>);

define method convert-to-chemical-description( version == #"creatures2", type :: <chemical> ) => (result :: <string>)
    element($chemical-descriptions, 
      type, 
      default: format-to-string("Unknown chemical: %=", type));
end method convert-to-chemical-description;

define method convert-to-chemical-description( version == #"creatures3", type :: <chemical> ) => (result :: <string>)
    element($c3-chemical-descriptions, 
      type, 
      default: format-to-string("Unknown chemical: %=", type));
end method convert-to-chemical-description;
