Module:    creatures-genes
Synopsis:  Classes for reading Creatures genetic files
Author:    Chris Double
Copyright: (C) 1998, Chris Double.  All rights reserved.
License:   See License.txt

define constant $pose-descriptions = #(
    "Reach low near",            // 0
    "Reach lowish near",
    "Reach highish near",
    "Reach high near",
    "Reach low medium",
    "Reach lowish medium",
    "Reach highish medium",
    "Reach high medium",
    "Reach low far",
    "Reach lowish far",
    "Reach highish far",        //10
    "Reach high far",
    "Stand",
    "Approach 1",
    "Approach 2",
    "Approach 3",
    "Approach 4",
    "Pain Approach 1",
    "Pain Approach 2",
    "Pain Approach 3",
    "Pain Approach 4",        //20
    "Tired Approach 1",
    "Tired Approach 2",
    "Tired Approach 3",
    "Tired Approach 4",
    "Fear Approach 1",
    "Fear Approach 2",
    "Fear Approach 3",
    "Fear Approach 4",
    "Anger Approach 1",
    "Anger Approach 2",    //30
    "Anger Approach 3",
    "Anger Approach 4",
    "To camera",
    "Express general need",
    "Express pain",
    "Express hunger",
    "Express tired",
    "Express lonely",
    "Express fear",
    "Toe tap 1",  //40
    "Toe tap 2",
    "Angry 1",
    "Angry 2",
    "Swing Arms 1",
    "Swing Arms 2",
    "Shiver 1",
    "Shiver 2",
    "Slap norn 5",
    "Walk away 1",
    "Walk away 2",//50
    "Walk away 3",
    "Walk away 4",
    "Flee 1",
    "Flee 2",
    "Flee 3",
    "Flee 4",
    "Rest",
    "Sleep",
    "East",
    "West", //60
    "Wander 1",
    "Wander 2",
    "Wander 3",
    "Wander 4",
    "Throw 1",
    "Throw 2",
    "Kick 1",
    "Kick 2",
    "Drum 1",
    "Drum 2",//70
    "Sneeze 1",
    "Sneeze 2",
    "Eat 1",
    "Eat 2",
    "Startled",
    "Kiss",
    "Dead",
    "Limp 1",
    "Limp 2",
    "Limp 3",//80
    "Limp 4",
    "Drunken Stagger 1",
    "Drunken Stagger 2",
    "Drunken Stagger 3",
    "Drunken Stagger 4",
    "Downhill 1",
    "Downhill 2",
    "Downhill 3",
    "Downhill 4",
    "Uphill 1",//90
    "Uphill 2",
    "Uphill 3",
    "Uphill 4",
    "Run 1",
    "Run 2",
    "Run 1b",
    "Run 2b",
    "Cough 1",
    "Cough 2",
    "Cough 3",//100
    "Cough 4",
    "Pushed 1",
    "Pushed 2",
    "Pushed 3",
    "Pushed 4",
    "Sneeze 3",
    "Lay egg 1",
    "Lay egg 2",
    "Lay egg 3",
    "Lay egg 4",//110
    "Slap norn 1",
    "Slap norn 2",
    "Slap norn 3",
    "Slap norn 4",
    "Falling 1",
    "Falling 2",
    "Impact 1",
    "Impact 2",
    "Impact 3",
    "Impact 4",//120
    "Impact 5",
    "Yawn 1",
    "Yawn 2",
    "Yawn 3",
    "Dance 1",
    "Dance 2",
    "Dance 3",
    "Dance 4",
    "Dance 5",
    "Dance 6",//130
    "Pushed behind 1",
    "Pushed behind 2",
    "Pushed behind 3",
    "Pushed behind 4",
    "Fast run 1",
    "Fast run 2",
    "Fast run 3",
    "Fast run 4",
    "Friendly scuttle 1",
    "Friendly scuttle 2",//140
    "Friendly scuttle 3",
    "Friendly scuttle 4",
    "Barf 1",
    "Barf 2",
    "Barf 3",
    "Barf 4",
    "Pickup 1",
    "Pickup 2",
    "Pickup 3",
    "Pickup 4",//150
    "Creep 1",
    "Creep 2",
    "Creep 3",
    "Creep 4",
    "Creep 5",
    "Jive 1",
    "Jive 2",
    "Jive 3",
    "Jive 4",
    "Jive 5",//160
    "Barf 5",
    "Teeter 1",
    "Teeter 2",
    "Teeter 3",
    "Teeter 4",
    "Teeter 5",
    "Totter 1",
    "Totter 2",
    "Totter 3",
    "Totter 4",//170
    "Pose 171",
    "Pose 172",
    "Pose 173",
    "Pose 174",
    "Pose 175",
    "Pose 176",
    "Pose 177",
    "Pose 178",
    "Pose 179",
    "Pose 180",//180
    "Pose 181",
    "Pose 182",
    "Pose 183",
    "Pose 184",
    "Pose 185",
    "Pose 186",
    "Pose 187",
    "Pose 188",
    "Pose 189",
    "Pose 190",//190
    "Pose 191",
    "Pose 192",
    "Pose 193",
    "Pose 194",
    "Pose 195",
    "Pose 196",
    "Pose 197",
    "Pose 198",
    "Pose 199",
    "Pose 200",//200
    "Pose 201",
    "Pose 202",
    "Pose 203",
    "Pose 204",
    "Pose 205",
    "Pose 206",
    "Pose 207",
    "Pose 208",
    "Pose 209",
    "Pose 210",//210
    "Pose 211",
    "Pose 212",
    "Pose 213",
    "Pose 214",
    "Pose 215",
    "Pose 216",
    "Pose 217",
    "Pose 218",
    "Pose 219",
    "Pose 220",//220
    "Pose 221",
    "Pose 222",
    "Pose 223",
    "Pose 224",
    "Pose 225",
    "Pose 226",
    "Pose 227",
    "Pose 228",
    "Pose 229",
    "Pose 230",//230
    "Pose 231",
    "Pose 232",
    "Pose 233",
    "Pose 234",
    "Pose 235",
    "Pose 236",
    "Pose 237",
    "Pose 238",
    "Pose 239",
    "Pose 240",//240
    "Pose 241",
    "Pose 242",
    "Pose 243",
    "Pose 244",
    "Pose 245",
    "Pose 246",
    "Pose 247",
    "Pose 248",
    "Pose 249",
    "Pose 250",//250
    "Pose 251",
    "Pose 252",
    "Pose 253",
    "Pose 254"
);
define method convert-to-pose-description( type :: <byte> ) => (result :: <string>)
    element($pose-descriptions, 
      type, 
      default: format-to-string("Unknown pose: %=", type));
end method convert-to-pose-description;
