Module:    creatures-genes
Synopsis:  Classes for reading Creatures genetic files
Author:    Chris Double
Copyright: (C) 1998, Chris Double.  All rights reserved.
License:   See License.txt

define constant <stimulus> = <byte>;
define constant $c2-base-stimulus-descriptions = #(
    "Disappointment",
    "Pointer pats me",
    "Creature pats me",
    "Pointer slaps me",
    "Creature slaps me",
    "It is approaching",
    "It is retreating",
    "I bump into wall",
    "Object comes into view",
    "Unrecognized word",
    "Heard user speak",
    "Heard creature speak",
    "I am quiescent",
    "I've Activated1",
    "I've Activated2",
    "I've Deactivated",
    "I am approaching",
    "I have retreated",
    "I have got",
    "I have dropped",
    "I've stated need",
    "I am Resting",
    "I am sleeping",
    "I am travelling",
    "I've been pushed",
    "I've been hit",
    "I've eaten something",
    "SPARE",
    "Invol 0='flinch'",
    "Invol 1='lay egg'",
    "Invol 2='sneeze'",
    "Invol 3='cough'",
    "Invol 4='shiver'",
    "Invol 5='sleep'",
    "Invol 6='languish'",
    "Invol 7='NA'",
    "Approaching edge",
    "Retreating from edge",
    "Falling through air",
    "Impact post fall",
    "Pointer has spoken 'Yes'",
    "Creature has spoken 'Yes'",
    "Pointer has spoken 'No'",
    "Creature has spoken 'No'",
    "I've performed a hit",
    "I've mated"
);

define constant $c3-base-stimulus-descriptions = #(
    "Disappointment",
    "Hand pats me",
    "Creature pats me",
    "Hand slaps me",
    "Creature slaps me",
    "Object is approaching (deprecated)",
    "Object is retreating (deprecated)",
    "I've hit a wall",
    "Visible event (deprecated)",
    "Heard unrecognised word (deprecated)",
    "Heard hand speak",
    "Heard creature speak",
    "I am Quiescent (Periodic)",
    "I have pushed",
    "I have pulled",
    "I have stopped",
    "I have approached (periodic)",
    "I have retreated",
    "I have gotten",
    "I have dropped",
    "I have said need",
    "I have rested",
    "I am sleeping (periodic)",
    "I am travelling (periodic)",
    "I've been pushed",
    "I've been hit",
    "I have eaten",
    "Ac6",
    "Involuntary 0",
    "Involuntary 1",
    "Involuntary 2",
    "Involuntary 3",
    "Involuntary 4",
    "Involuntary 5",
    "Involuntary 6",
    "Involuntary 7",
    "Approaching an edge (deprecated)",
    "Retreating from an edge (deprecated)",
    "Falling through the air (deprecated)",
    "Hitting the ground post fall (deprecated)",
    "Hand has said yes",
    "Creature has said yes",
    "Hand has said no",
    "Creature has said no",
    "I have hit",
    "I have mated",
    "opposite sex tickle",
    "same sex tickle",
    "Go nowhere",
    "Go in",
    "Go out",
    "Go up",
    "Go down",
    "Go left",
    "Go right",
    "Reached peak of smell 0",
    "Reached peak of smell 1",
    "Reached peak of smell 2",
    "Reached peak of smell 3",
    "Reached peak of smell 4",
    "Reached peak of smell 5",
    "Reached peak of smell 6",
    "Reached peak of smell 7",
    "Reached peak of smell 8",
    "Reached peak of smell 9",
    "Reached peak of smell 10",
    "Reached peak of smell 11",
    "Reached peak of smell 12",
    "Reached peak of smell 13",
    "Reached peak of smell 14",
    "Reached peak of smell 15",
    "Reached peak of smell 16",
    "Reached peak of smell 17",
    "Reached peak of smell 18",
    "Reached peak of smell 19",
    "Wait",
    "Discomfort",
    "Eaten plant",
    "Eaten fruit",
    "Eaten food",
    "Eaten animal",
    "Eaten detritus",
    "Consume alcohol",
    "Danger plant",
    "Friendly plant",
    "Play bug",
    "Play critter",
    "Hit critter",
    "Play danger animal",
    "Activate button",
    "Activate machine",
    "Got machine",
    "Hit machine",
    "Got creature egg",
    "Travelled in lift",
    "Travelled through meta door",
    "Travelled through internal door",
    "Played with toy"
);


define constant $c2-stimulus-descriptions = 
    concatenate($c2-base-stimulus-descriptions,
      map(method(x) format-to-string("Unknown Stimulus %=", x) end, 
          range(from: $c2-base-stimulus-descriptions.size, to: 253 - $c2-base-stimulus-descriptions.size)));

define constant $c3-stimulus-descriptions = 
    concatenate($c3-base-stimulus-descriptions,
      map(method(x) format-to-string("Unknown Stimulus %=", x) end, 
          range(from: $c3-base-stimulus-descriptions.size, to: 253 - $c3-base-stimulus-descriptions.size)));

define method convert-to-stimulus-description( version == #"creatures2", type :: <stimulus> ) => (result :: <string>)
    element($c2-stimulus-descriptions, 
      type, 
      default: format-to-string("Unknown Stimulus: %=", type));
end method convert-to-stimulus-description;

define method convert-to-stimulus-description( version == #"creatures3", type :: <stimulus> ) => (result :: <string>)
    element($c3-stimulus-descriptions, 
      type, 
      default: format-to-string("Unknown Stimulus: %=", type));
end method convert-to-stimulus-description;

