Origin: COM-type-library
Type-library: C:\WINDOWS\SYSTEM\MSXML3.DLL
Module: type-library-module
Module-file: type-library-module.dylan
Generate: dispatch-clients
Stub-file: stubs.dylan
Interfaces: IXMLDOMImplementation
            IXMLDOMNode
            IXMLDOMNodeList
            IXMLDOMNamedNodeMap
            IXMLDOMDocument
            IXMLDOMDocumentType
            IXMLDOMElement
            IXMLDOMAttribute
            IXMLDOMDocumentFragment
            IXMLDOMText
            IXMLDOMCharacterData
            IXMLDOMComment
            IXMLDOMCDATASection
            IXMLDOMProcessingInstruction
            IXMLDOMEntityReference
            IXMLDOMParseError
            IXMLDOMSchemaCollection
            IXMLDOMDocument2
            IXMLDOMNotation
            IXMLDOMEntity
            IXTLRuntime
            IXSLTemplate
            IXSLProcessor
            ISAXXMLReader
            ISAXEntityResolver
            ISAXContentHandler
            ISAXLocator
            ISAXAttributes
            ISAXDTDHandler
            ISAXErrorHandler
            ISAXXMLFilter
            ISAXLexicalHandler
            ISAXDeclHandler
            IVBSAXXMLReader
            IVBSAXEntityResolver
            IVBSAXContentHandler
            IVBSAXLocator
            IVBSAXAttributes
            IVBSAXDTDHandler
            IVBSAXErrorHandler
            IVBSAXXMLFilter
            IVBSAXLexicalHandler
            IVBSAXDeclHandler
            IMXWriter
            IMXAttributes
            IMXReaderControl
            IXMLElementCollection
            IXMLDocument
            IXMLElement
            IXMLDocument2
            IXMLElement2
            IXMLAttribute
            IXMLError
            _xml_error
            IXMLDOMSelection
            XMLDOMDocumentEvents
            IDSOControl
            IXMLHTTPRequest
            IServerXMLHTTPRequest
            DOMDocument
            DOMDocument26
            DOMDocument30
            FreeThreadedDOMDocument
            FreeThreadedDOMDocument26
            FreeThreadedDOMDocument30
            XMLSchemaCache
            XMLSchemaCache26
            XMLSchemaCache30
            XSLTemplate
            XSLTemplate26
            XSLTemplate30
            DSOControl
            DSOControl26
            DSOControl30
            XMLHTTP
            XMLHTTP26
            XMLHTTP30
            ServerXMLHTTP
            ServerXMLHTTP30
