#!/bin/sh

PROGRAMS="cop robber"
PACKAGE=submission.tgz

cd $(dirname $0)
rm -rf submission submission.tgz

mkdir -p submission/bin
cp $(ldd $(which d2c) | grep libgc | awk '{print $3}') submission/bin
cp README submission

(cd src; make) || (echo make failed; exit 1)
cp src/bot-driver/bot-driver submission/bin
strip submission/bin/bot-driver

make_driver (){
    prog=$1
    bot_type=$2
    cat >submission/$prog <<-END
	#!/bin/sh
	US=\$(dirname \$0)
	LD_LIBRARY_PATH=\${US}/bin:\${LD_LIBRARY_PATH}
	export LD_LIBRARY_PATH
	exec \${US}/bin/bot-driver $bot_type 2>/dev/null
	END
    chmod +x submission/$prog
}

make_driver cop stupid-predicting-cop
make_driver robber bruce-robber

cp -r src submission
for prog in ${PROGRAMS} shared; do (cd submission/src/$prog; make clean); done
find submission/src -name .svn | xargs rm -rf

tar zcf ${PACKAGE} submission
